<a href="https://colab.research.google.com/github/sourovdeybd71/World-Of-Machine-Learning/blob/main/PythonBasic_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Sigmoid Function
import math

#formula: sigmoid(x)= 1/1+e^(-x)
def sigmoid(x):
  s= 1/(1+math.exp(-x))
  return s
sigmoid(3)

0.9525741268224334

We rarely use the "math" library in deep learning because the inputs of the functions are real numbers. In deep learning we mostly use matrices and vectors. This is why numpy is more useful.

In [ ]:
#sIGMOID using numpy
import numpy as np
def sigmoid(x):
  s= 1/(1+np.exp(-x))
  return s

x = np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

**Reshaping Arrays**

Implement image2vector() that takes an input of shape (length, height, 3) and returns a vector of shape (length*height*3, 1). For example, if you would like to reshape an array v of shape (a, b, c) into a vector of shape (a*b,c) you would do:

v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c

In [ ]:
def image2vector(image):
  v=image.reshape(image.shape[0]*image.shape[1]*image.shape[2], 1)
  return v

In [ ]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


**VECTORIZATION**

*Classic Methods*

In [9]:
import numpy as np
import time

x1 = [1, 2, 3]
x2 = [4, 5, 6]


#dot product (Classic Method)
tic = time.process_time()
dot=0
for i in range(len(x1)):
  dot+=x1[i]*x2[i]

toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

#outer product (Classic Method)
tic = time.process_time()
#create a len(x1)*len(x2) matrix with only zeros
outer = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
  for j in range(len(x2)):
    outer[i, j] = x1[i]*x2[j]

toc= time.process_time()
print("outer = "+str(outer)+"\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

#elementwise multiplication (Classic Method)
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]

toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")






dot = 32
 ----- Computation time = 0.10231100000002158ms
outer = [[ 4.  5.  6.]
 [ 8. 10. 12.]
 [12. 15. 18.]]
 ----- Computation time = 0.3194719999992657ms
elementwise multiplication = [ 4. 10. 18.]
 ----- Computation time = 0.2362259999992844ms


*Vectorized Methods*

In [10]:
x1 = [1, 2, 3]
x2 = [4, 5, 6]
#dot product
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

#outer product
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

#elementwise
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


dot = 32
 ----- Computation time = 0.21064099999978936ms
outer = [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
 ----- Computation time = 0.19762799999956115ms
elementwise multiplication = [ 4 10 18]
 ----- Computation time = 0.153845999999902ms


**LOSS Calculation**

L1 (y-hat, y) = SUM(i=0 to i=m) |y(i) - y-hat(i)|

L2 (y-hat, y) = SUM(i=0 to i=m) [y(i) - y-hat(i)]^2

In [15]:
def L1(yhat, y):
  loss = sum(abs(yhat-y))
  return loss

yhat = np.array([12, 32, 5])
y = np.array([12, 14, 7])
#12-12=0, 32-14= 18, 5-7=2
#0+18+2=20
#expected loss = 20
print("L1= "+str(L1(yhat, y)))

L1= 20


In [19]:
def L2(yhat, y):
  x = yhat - y
  #np.dot(x,x) will do the square calculation
  loss = np.dot(x,x)
  return loss

yhat = np.array([12, 32, 5])
y = np.array([12, 14, 7])

print("L2= "+str(L2(yhat, y)))

L2= 328
